// Generated by CoffeeScript 1.6.3
(function() {
  var http, onReady, port, server, use;

  if (typeof isNodeJs === "undefined" || typeof runTest === "undefined") {
    (function() {
      var root;
      root = typeof window === "undefined" ? global : window;
      if (typeof isNodeJs === "undefined") {
        root.isNodeJs = typeof window === "undefined";
      }
      if (typeof isPhoneGap === "undefined") {
        root.isPhoneGap = typeof document.ondeviceready !== "undefined";
      }
      if (typeof runTest === "undefined") {
        return root.runTest = true;
      }
    })();
  }

  use = isNodeJs ? (function(module) {
    return require(module);
  }) : (function(module) {
    return window[module];
  });

  onReady = function(fn) {
    if (isNodeJs) {
      return process.nextTick(fn);
    } else {
      if (document.readystate !== "complete") {
        return fn();
      } else {
        return setTimeout((function() {
          return onReady(fn);
        }), 17);
      }
    }
  };

  port = process.env.API_PORT || 4444;

  http = require("http");

  server = http.createServer(function(req, res) {
    console.log(req);
    res.writeHead(200, {
      "Content-Type": "text/plain"
    });
    return res.end("helo");
  });

  server.listen(port, "localhost");

  onReady(function() {
    return console.log("serving on port " + port);
  });

}).call(this);
